FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /app

# Copy everything
COPY . ./
# Restore as distinct layers
RUN dotnet restore --disable-parallel
# Build and publish a release
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app

# Copy the build output
COPY --from=build-env /app/out .

# Install native dependencies required by wkhtmltox
RUN apt-get update && apt-get install -y \
    libxrender1 libxext6 libfontconfig1 \
    && rm -rf /var/lib/apt/lists/*

# Ensure the shared library is accessible
COPY --from=build-env /app/out/libwkhtmltox.so /usr/lib/libwkhtmltox.so

ENTRYPOINT ["dotnet", "company-man.dll"]
